# Generated by Django 5.1 on 2024-08-27 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CarParkInfo",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("carpark_id", models.CharField(max_length=180)),
                ("name", models.CharField(max_length=180)),
                ("lot_type", models.CharField(default="C", max_length=5)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("total_capacity", models.IntegerField()),
                ("agency", models.CharField(max_length=180)),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "carpark_info",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="CarParkAvailability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=180)),
                ("lot_type", models.CharField(default="C", max_length=5)),
                ("available_lot", models.IntegerField()),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "carpark",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="carPark.carparkinfo",
                    ),
                ),
            ],
            options={
                "db_table": "carpark_availability",
                "managed": True,
            },
        ),
    ]
