# Generated by Django 5.1 on 2024-08-28 01:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("carPark", "0002_carparkinfo_unique_carpark"),
    ]

    operations = [
        migrations.RenameField(
            model_name="carparkavailability",
            old_name="carpark",
            new_name="info",
        ),
    ]
