# Generated by Django 5.1 on 2024-08-29 17:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("carPark", "0003_rename_carpark_carparkavailability_info"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="carparkavailability",
            name="lot_type",
        ),
        migrations.RemoveField(
            model_name="carparkavailability",
            name="name",
        ),
    ]
